<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
#input matrix
A = [[1,2],[3,4]]
B = [[1,2,3,4,5],[5,6,7,8,9]]

#mitilication function
def matrix_mul(A,B):
    '''
    This function conduct row wise multiplication
    '''
    result = [A[i] * B[i] for i in range(0,len(A))]
    return sum(result)
  
if len(A[0]) == len(B):
    #Checks weather the matrix multiplication is possible or not
    #transpose of a matrix
    #intiution from Apllied Al lectures
    B_trans = [[row[i] for row in B] for i in range(len(B[0]))]

    #creating empty list to store final result
    product = list()

    #for loop to calculate the product and append them in product matrix
    for x in A:
        #takes row elements in matrix A
        row_product = list()
        #takes row elements in Transpose matrix
        for y in B_trans:
            #conducts row wise multiplication by calling matrix_mul function
            row_product.append(matrix_mul(x,y))
            #append the final result to the list
        product.append(row_product)
    print("The product of the given two matrix\n", product)
else:
    print("The multiplication is Not possible")

The product of the given two matrix
 [[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
A = [0,5,27,6,13,28,100,45,10,79]

#importing random for generating the random values for sampling
import random

#dividing each element with sum of the list A to normalize the list
A_dash = [i/sum(A) for i in A]

#calculating cummalative sum 
cummalative = list()
number = 0
for i in A_dash:
  number += i
  cummalative.append(number)

#creates the dictionary with cummalative scores as key and elements of A as values
dictionary = dict(zip(cummalative,A))

def pick_a_number_from_list(A):
    '''
    This function picks the random number
    '''
    #generate uniform number
    r = random.uniform(0.0,1.0)
    
    number = 0
    for i in range(len(cummalative)):
        #for loop checks random numbers
        if (r >= number):
            number = cummalative[i]
    return dictionary[number]

def count(a):
    '''
    This function counts number of element in the list
    '''
    num = 0 
    for i in sampling_based_on_magnitued:
       if i == a:
         num += 1
    return num

#creating a list of 1000 sampled values with sorting
sampling_based_on_magnitued = sorted([pick_a_number_from_list(i) for i in range(10000)])

#printing the frequency of each elements after proportional sampling
for i in sorted(A):
  print("The frequency of {} in a sampled list {}".format(i,count(i)))

The frequency of 0 in a sampled list 0
The frequency of 5 in a sampled list 153
The frequency of 6 in a sampled list 187
The frequency of 10 in a sampled list 327
The frequency of 13 in a sampled list 391
The frequency of 27 in a sampled list 876
The frequency of 28 in a sampled list 843
The frequency of 45 in a sampled list 1411
The frequency of 79 in a sampled list 2511
The frequency of 100 in a sampled list 3301


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re

#List of inputs
A = ['234',"a2b3c4","abc","#2a$#b%c%561#"]

#loop to print the output
for string in A:
  print("Input : ", string)

  #finding the numbers in the string
  x = re.findall('[0-9]', string)

  print("Output : ",'#' * len(x))
  print(" ")

Input :  234
Output :  ###
 
Input :  a2b3c4
Output :  ###
 
Input :  abc
Output :  
 
Input :  #2a$#b%c%561#
Output :  ####
 


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

#dictionary creation with marks as keys and students as values
dictionary = dict(zip(Marks, Students))

def top_5_ranks():
    '''
    This function prints least 5 ranks
    '''
    #printing the top 5 marks
    for i in sorted(dictionary.keys(), reverse = True)[:5]:
      print(dictionary[i],i)

def least_5_ranks():
    '''
    This function prints top 5 ranks
    '''
    #printing the least 5 marks
    for i in sorted(dictionary.keys())[:5]:
      print(dictionary[i], i)

def interquartile_range():
    '''
    This function calculate the percentiles of the given number
    '''
    #intuition from the evaluator 
    #calculating max and min of marks list
    max_mark = max(Marks)
    min_mark = min(Marks)

    #calculating difference between max and min
    diff = max_mark - min_mark

    #calculating 25th and 75th percentile
    pre_25 = diff*0.25
    pre_75 = diff*0.75

    #priniting the output
    for i in sorted(Marks):
      if pre_25 < i < pre_75:
        print(dictionary[i],i)

#calling the all the function
print("The top 5 ranks in the given list")
top_5_ranks()

print("\nThe least 5 ranks in the given list")
least_5_ranks()

print("\nThe marks between >25th percentile <75th percentile ")
interquartile_range()

The top 5 ranks in the given list
student8 98
student10 80
student2 78
student5 48
student7 47

The least 5 ranks in the given list
student3 12
student4 14
student9 22
student6 43
student1 45

The marks between >25th percentile <75th percentile 
student9 22
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [5]:
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

#creating separate list for x and y values
x_values = [i[0] for i in S]
y_values = [i[1] for i in S]

#importing math library for cosine inverse and square root operation
import math

#creating the empty list for inputing the cosine similarities
cosine_distance_list = list()

def cosine_similarities():
    '''
    This function calculates the cosine similarity between given points
    '''
    cosine = 1

    #calculating the cosine similarities
    for i in range(len(S)):
        cosine = math.acos(((x_values[i] * P[0]) + (y_values[i] * P[1])) / ((math.sqrt(x_values[i]**2 + y_values[i]**2)) * (math.sqrt(P[0]**2 + P[1]**2))))
        cosine_distance_list.append(cosine) #appending the values

#calling the function
cosine_similarities()

#creation of dictionary with cosine similarity as key and points in S as values
dictionary = dict(zip(cosine_distance_list, S))

#printing the 5 closest points
print("The 5 closest points(based on cosine distance) in S from P")
for i in sorted(dictionary.keys())[:5]:
    print(dictionary[i])

The 5 closest points(based on cosine distance) in S from P
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [6]:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

#importing regular operation expressions for separating variables in "ax+by+c" 
import re

def string_splitting(a):
    '''
    This function splits the strings
    '''
    #strings are splitted using re operations
    splitted = re.split(r"[a-zA-Z]", a)

    #the splitted strings are stored in list for better handling
    co_efficients = [float(i) for i in splitted]
    
    return (co_efficients[:2],co_efficients[-1])

def caluclation(a,b):
    '''
    This function finds the distance
    '''
    #coeffeicients of a and b are stored 
    co_eff = string_splitting(a)[0]

    #the coefficients are multiplied with the given points
    w_values = [co_eff[i] * b[i] for i in range(len(b))]
    
    #the sum of all w values with the addition of the interceptor
    return (sum(w_values) + string_splitting(a)[1])

def i_am_the_one(a,b):
    '''
    This function checks the line is separable or not
    '''
    if caluclation(a,b) >= 0:
      return 1
    else:
      return 0

def results(i):
    '''
    This function checks the lines separates the given points
    '''
    #creates two list
    blue_list = [(i_am_the_one(i,j)) for j in Blue]
    red_list = [(i_am_the_one(i,k)) for k in Red]
    
    #checking weather both list have different boolen values
    if (all(blue_list)) != (all(red_list)):
      return ("YES")
    else:
      return ("NO")

print("OUTPUT:")
for i in Lines:
    print(results(i))

OUTPUT:
YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [7]:
List = ["_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]

def curve_smoothing(i):
    '''
    This function fills the blanks
    '''
    #calling the global variables
    global a
    global b
    global c

    #calculating the average
    average = ((c+i)/(a-b))

    #assigning the average to previous numbers
    for j in range(b,a):
      String[j] = int(average)

    #saving the values for next iteration
    c = average 
    b = a-1
  
for String in List:
  #assigning values for variables
  a = b = c = 0
  
  #For loop to smoothing
  print("Input : ", String)
  String = String.split(",")
  for i in String:
      if i == '_':
          a += 1
      else:
          a += 1
          curve_smoothing(int(i))

  #reversing the string
  String.reverse()

  #reassiging the variables for next iteration
  a = b = c = 0

  #For loop to check the missing values in the end
  for i in String:
      if i == '_':
        a += 1
      else:
        a += 1
        curve_smoothing(int(i))
        break #breaking the loop to avoid futher smoothing

  #reversing the string to orginal format
  String.reverse()

  #printing the final string
  print("Output : ", end = "")
  for i in String:
    print(i, end = ",")
  print("\n")

Input :  _,_,_,24
Output : 6,6,6,6,

Input :  40,_,_,_,60
Output : 20,20,20,20,20,

Input :  80,_,_,_,_
Output : 16,16,16,16,16,

Input :  _,_,30,_,_,_,50,_,_
Output : 10,10,12,12,12,12,4,4,4,



<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

#creating empty list
S = list()
F = list()

#separating F's and S's
for i in A:
  if i[0] not in F:
    F.append(i[0])
  if i[1] not in S:
    S.append(i[1])

def computing(a,b):
    '''
    This function compute the conditional probabilites
    '''
    #assiging variables
    number1 = number2 = 0
    lst = list()
    
    #loop to separates S's
    for i in A:
      #takes the word from the A
      for j in i:
        #takes the word from the i
        if j == a:
          #if the word in i and A are same then 1 is added to number1 and i is appended to list
          number1 += 1
          lst.append(i)

    #loop to separates F's
    for i in lst:
      #takes the word from the list
      for j in i:
        #takes the word from the i
        if j == b:
          #if the word in i and A are same then 1 is added to number2
          number2 += 1
    return (number2,number1)
    
#calling function
for i in F:
  for j in S:
    print("P(F={}|S=={}) = {}/{}".format(i,j,computing(j,i)[0],computing(j,i)[1]), end = "     ")
  print("\n")

P(F=F1|S==S1) = 1/4     P(F=F1|S==S2) = 1/3     P(F=F1|S==S3) = 0/3     

P(F=F2|S==S1) = 1/4     P(F=F2|S==S2) = 1/3     P(F=F2|S==S3) = 1/3     

P(F=F3|S==S1) = 0/4     P(F=F3|S==S2) = 1/3     P(F=F3|S==S3) = 1/3     

P(F=F4|S==S1) = 1/4     P(F=F4|S==S2) = 0/3     P(F=F4|S==S3) = 1/3     

P(F=F5|S==S1) = 1/4     P(F=F5|S==S2) = 0/3     P(F=F5|S==S3) = 0/3     



<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

#splitting the strings of words
S1 = S1.split()
S2 = S2.split()

#calculating the common words between the strings
common_words = 0
for i in S1:
  #takes the word from the S1
  for j in S2:
    #takes the word from the S2
    if i == j:
      #the word picked from the both strings. If they are equal, adds 1 to the common words variable.
      common_words += 1
      #breaks the second loop to avoid double count of the common words
      break

#Findings the words in S1 not in S2
#empty list to store the words which are in S1 not in S2
S1_list = list() 
for i in S1:
  #takes the word from the S1
  if i not in S2:
    #if the word is present S2 it will append to the list
    S1_list.append(i)

#Findings the words in S2 not in S1
#empty list to store the words which are in S2 not in S1
S2_list = list()
for i in S2:
  #takes the word from the S2
  if i not in S1:
    #if the word is present S1 it will append to the list
    S2_list.append(i)

#printing the results
print("Number of common words between S1, S2 : ", common_words)
print("Words in S1 but not in S2 :", S1_list)
print("Words in S2 but not in S1 :", S2_list)

Number of common words between S1, S2 :  7
Words in S1 but not in S2 : ['first', 'F', '5']
Words in S2 but not in S1 : ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

#importing math library for log10 function
import math

#summation of log loss
log_loss = 0
for i in A:
  if i[0] == 1:
    #calculating the log loss for values equal to 1 and adding to the total 
    log_loss += (int(i[0]) * math.log10(float(i[1])))
  else:
    #calculating the log loss for values equal to 0 and adding to the total 
    log_loss += ((int(1-i[0]) * math.log10(1-float(i[1]))))
  
#dividing the log loss with the total n with negative to it
log_loss = log_loss * -1/len(A)

#printing the answer with precision 
print(round(log_loss,7))

0.4243099
